/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Axel' at '2/25/16 6:24 PM' with Gradle 2.6
 *
 * @author Axel, @date 2/25/16 6:24 PM
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
