import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Axel' at '2/25/16 6:24 PM' with Gradle 2.6
 *
 * @author Axel, @date 2/25/16 6:24 PM
 */
public class LibraryTest {
	@Test public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
